### PR TITLE
feat: add move to player

### PR DESCRIPTION
**Pull request by JheremyTancara**
# Pull Request

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality
      to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by JeferssonCL — DISMISSED** [review]
Good job

**Comment by denis-gandel** [comment]
Screenshot from 2024-06-12 10-34-00

El PLAYER se queda volando en zonas donde deberia ya caer, debido a que en el Mario Original:
https://drive.google.com/file/d/1IMTZHprHQoLmczzbwxQnWCQ-0Vbbwr9P/view?usp=sharing

**Review by JeferssonCL — DISMISSED** [review]

**Comment by denis-gandel** [comment]
https://drive.google.com/file/d/1ri1x6ANwyiowcGsgt1qObEaZtdBHKrHj/view?usp=sharing

There is a small bug that when the player falls he can jump into the void and it is not detected that there is no block, unless the player has not jumped before in which case it works normally.

**Review by JeferssonCL — APPROVED** [review]

**Review by denis-gandel — APPROVED** [review]
Good :D

**Pull request merged**
