### PR TITLE
feat: victory cinematic

### PR DESCRIPTION
**Pull request by denis-gandel**
# Pull Request

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality
      to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by daniel-espinoza-79 — APPROVED** [review]
Great Job!

**Comment by JeferssonCL** [comment]
I don't know why but the cinematic have a delay, the hero does not disappear  and also there is no time to burn the score, please check.
expected:
https://drive.google.com/file/d/1VBSEP0GTN1aIAwmhov73Y4vRFjtb2obz/view?usp=sharing
actual:
https://drive.google.com/file/d/1HjbyRRa7PbmqR3k-Z5eNMOZUDwUDlI4D/view?usp=sharing

**Review by JeferssonCL — CHANGES_REQUESTED** [review]
please solve observations

**Review by JeferssonCL — APPROVED** [review]
No observations

**Pull request merged**
